# Generated by Django 5.2.6 on 2025-09-27 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('plus_one', 'Plus One'), ('plus_two', 'Plus Two')], max_length=50)),
                ('year', models.IntegerField()),
                ('section', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
