# Generated by Django 5.2.6 on 2025-09-28 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_fee_paid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fee',
            name='balance_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
