# Generated by Django 5.2.6 on 2025-09-28 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_fee_balance_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='section',
            field=models.CharField(choices=[('a', 'Batch A'), ('b', 'Batch B')], default='A', max_length=10),
        ),
    ]
