# Generated by Django 5.2.6 on 2026-06-01 11:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_mark'),
    ]

    operations = [
        migrations.AddField(
            model_name='mark',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='mark',
            name='obtained_mark',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='mark',
            name='percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=6),
        ),
        migrations.AlterField(
            model_name='mark',
            name='total_mark',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
