# Generated by Django 5.2.6 on 2026-06-18 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_mark_batch_alter_mark_obtained_mark_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('logo', models.ImageField(upload_to='institute_logos/')),
                ('established_date', models.DateField()),
            ],
        ),
    ]
