# Generated by Django 5.2.6 on 2025-09-28 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_batch_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='section',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
