# Generated by Django 5.2.6 on 2025-10-20 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_alter_batch_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='classs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
