# Generated by Django 5.2.6 on 2026-08-10 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_exam_date_exam_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
