# Generated by Django 5.2.6 on 2025-10-20 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0008_remove_batch_section_batch_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='name',
        ),
    ]
