# Generated by Django 5.2.6 on 2026-08-10 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0009_exam_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='exam',
            name='timetable',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_exam': True}, null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.timetable'),
        ),
    ]
