# Generated by Django 5.2.6 on 2026-08-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_timetable_is_exam_alter_exam_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='pass_mark',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
