# Generated by Django 5.2.6 on 2026-08-16 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0011_exam_pass_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='exam_name',
        ),
        migrations.AddField(
            model_name='mark',
            name='exam',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='marks', to='academics.exam'),
        ),
    ]
