# Generated by Django 5.2.6 on 2026-08-16 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0012_remove_mark_exam_name_mark_exam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='total_mark',
        ),
    ]
