# Generated by Django 5.2.6 on 2026-08-16 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_remove_mark_total_mark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mark',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='mark',
            name='subject',
        ),
    ]
