# Generated by Django 5.2.6 on 2026-08-16 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0014_remove_mark_batch_remove_mark_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='question_paper',
            field=models.FileField(blank=True, null=True, upload_to='question_papers/'),
        ),
    ]
