# Generated by Django 5.2.6 on 2026-08-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_exam_question_paper'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='batch',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='academics.institute'),
        ),
        migrations.AddField(
            model_name='exam',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='academics.institute'),
        ),
        migrations.AddField(
            model_name='fee',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='academics.institute'),
        ),
        migrations.AddField(
            model_name='timetable',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='academics.institute'),
        ),
        migrations.AlterUniqueTogether(
            name='batch',
            unique_together={('institute', 'classs', 'year')},
        ),
    ]
