# Generated by Django 5.2.6 on 2026-02-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_batch_classs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='batch',
        ),
        migrations.AlterField(
            model_name='batch',
            name='classs',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
