# Generated by Django 5.2.6 on 2026-09-02 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_batch_unique_together_batch_institute_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='institute',
            name='currency_code',
            field=models.CharField(default='INR', max_length=10),
        ),
        migrations.AddField(
            model_name='institute',
            name='domain',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='institute',
            name='enable_pf',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='institute',
            name='enable_tax',
            field=models.BooleanField(default=False),
        ),
    ]
