# Generated by Django 5.2.6 on 2026-09-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0017_batch_section_fee_description_payroll'),
        ('academics', '0017_institute_currency_code_institute_domain_and_more'),
    ]

    operations = [
    ]
