# Generated by Django 5.2.6 on 2026-09-03 06:53
# NOTE: column already existed in DB from prior session; using SeparateDatabaseAndState
# to update migration state without re-running the DDL.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0018_merge_20260903_0515'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            database_operations=[],  # skip DDL — column already exists
            state_operations=[
                migrations.AddField(
                    model_name='institute',
                    name='created_at',
                    field=models.DateTimeField(auto_now_add=True, null=True),
                ),
            ]
        ),
    ]
