# Generated by Django 5.2.6 on 2026-09-03 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0019_institute_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institute',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
