# Generated by Django 5.2.6 on 2026-09-12 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0021_grade'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='grade',
            name='grade_percentages_between_zero_and_hundred',
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.CheckConstraint(condition=models.Q(('max_percentage__lte', 100), ('min_percentage__gte', 0)), name='grade_percentages_between_zero_and_hundred'),
        ),
    ]
