# Generated by Django 5.2.6 on 2026-09-12 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0022_remove_grade_grade_percentages_between_zero_and_hundred_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='section',
        ),
    ]
