# Generated by Django 5.2.6 on 2026-09-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0023_remove_batch_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fee',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
