# Generated by Django 5.2.6 on 2026-10-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0024_alter_fee_due_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetable',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
