# Generated by Django 5.2.6 on 2025-10-20 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_subject_batch'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='batch',
            new_name='classs',
        ),
    ]
