# Generated by manually fixing circular dependency
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subject.subject'),
        ),
    ]
