# Generated by Django 5.2.6 on 2026-04-23 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subject.subject'),
        ),
        migrations.AddField(
            model_name='userdata',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
