# Generated by Django 5.2.6 on 2026-05-03 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_initial'),
        ('account', '0002_user_subject'),
    ]

    operations = [
    ]
