# Generated by Django 5.2.6 on 2025-09-28 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_alter_batch_section'),
        ('account', '0002_remove_userdata_batch_type_userdata_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.batch'),
        ),
    ]
