# Generated by Django 5.2.6 on 2026-06-25 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userdata_subject_userdata_user_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
