# Generated by Django 5.2.6 on 2026-07-15 05:26

import django.db.models.deletion
from django.db import migrations, models
import datetime

def set_institute_for_admins(apps, schema_editor):
    Institute = apps.get_model('academics', 'Institute')
    UserData = apps.get_model('account', 'UserData')
    inst = Institute.objects.first()
    if not inst:
        inst = Institute.objects.create(
            name='Default Institute',
            address='Default address',
            logo='default.png',
            established_date=datetime.date.today()
        )
    UserData.objects.filter(user_type='admin', institute__isnull=True).update(institute=inst)


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_institute'),
        ('account', '0003_alter_userdata_password'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userdata',
            options={},
        ),
        migrations.AddField(
            model_name='userdata',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admins', to='academics.institute'),
        ),
        
        migrations.RunPython(
            code=set_institute_for_admins,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'admin'), _negated=True), ('institute__isnull', False), _connector='OR'), name='admin_must_have_institute'),
        ),
    ]
