# Generated by Django 5.2.6 on 2025-09-28 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userdata_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='section',
        ),
    ]
