# Generated by Django 5.2.6 on 2026-08-18 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_alter_userdata_options_userdata_institute_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin'), ('superadmin', 'Superadmin')], max_length=10),
        ),
    ]
