# Generated by Django 5.2.6 on 2025-10-04 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userdata_section'),
        ('subject', '0002_subject_batch'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subjects', to='subject.subject'),
        ),
    ]
