# Generated by Django 5.2.6 on 2025-10-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_userdata_subject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userdata',
            old_name='batch',
            new_name='classs',
        ),
        migrations.AlterField(
            model_name='userdata',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('admin', 'Admin')], max_length=10),
        ),
    ]
