# Generated by Django 5.2.6 on 2026-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userdata_user_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='roll_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
