# Generated by Django 5.2.6 on 2026-08-27 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_userdata_user_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='roll_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
