# Generated by Django 5.2.6 on 2026-08-31 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_remove_userdata_date_of_birth_userdata_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
