# Generated by Django 5.2.6 on 2026-08-27 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_userdata_roll_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
        ),
    ]
