# Generated by Django 5.2.6 on 2025-10-20 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0013_alter_batch_year'),
        ('account', '0006_rename_batch_userdata_classs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_class', to='academics.batch'),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='classs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students_in_batch', to='academics.batch'),
        ),
    ]
