# Generated by Django 5.2.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userdata_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10, null=True),
        ),
    ]
