# Generated by Django 5.2.6 on 2025-10-20 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userdata_batch_alter_userdata_classs'),
        ('subject', '0003_rename_batch_subject_classs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='subject',
        ),
        migrations.AddField(
            model_name='userdata',
            name='subject',
            field=models.ManyToManyField(blank=True, related_name='teachers', to='subject.subject'),
        ),
    ]
