# Generated by Django 5.2.6 on 2026-08-31 18:16
# Edited: profile and roll_no already exist in DB (added by an earlier stashed
# migration that was applied directly on the server). AlterField is also skipped
# for gender because the column already has max_length=20 on the server.
# We use RunSQL with IF NOT EXISTS guards so this migration is idempotent
# (safe to run on both local dev DB and the production server).

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_userdata_date_of_birth'),
    ]

    operations = [
        migrations.RunSQL(
            sql=[
                ("ALTER TABLE account_userdata ADD COLUMN IF NOT EXISTS profile VARCHAR(100) NULL;", []),
                ("ALTER TABLE account_userdata ADD COLUMN IF NOT EXISTS roll_no VARCHAR(50) NULL;", []),
            ],
            reverse_sql=[
                ("ALTER TABLE account_userdata DROP COLUMN IF EXISTS profile;", []),
                ("ALTER TABLE account_userdata DROP COLUMN IF EXISTS roll_no;", []),
            ],
            state_operations=[
                migrations.AddField(
                    model_name='userdata',
                    name='profile',
                    field=models.ImageField(blank=True, null=True, upload_to='profiles/'),
                ),
                migrations.AddField(
                    model_name='userdata',
                    name='roll_no',
                    field=models.CharField(blank=True, max_length=50, null=True),
                ),
            ]
        ),
        migrations.AlterField(
            model_name='userdata',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
