# Generated by Django 5.2.6 on 2026-09-02 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_userdata_profile_userdata_roll_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='has_salary_config',
            field=models.BooleanField(default=False),
        ),
    ]
