# Generated by Django 5.2.6 on 2026-08-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_userdata_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='designation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='doj',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='has_salary_config',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userdata',
            name='qualification',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
