# Generated by Django 5.2.6 on 2026-09-03 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_add_has_salary_config'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdata',
            name='roll_number',
        ),
    ]
