# Generated by Django 5.2.6 on 2026-10-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0025_timetable_created_at'),
        ('account', '0011_alter_userdata_gender'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('subject', '0003_chapter_topic'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='userdata',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user_type', 'student'), _negated=True), models.Q(('roll_no__isnull', False), models.Q(('roll_no', ''), _negated=True)), _connector='OR'), name='student_must_have_roll_no'),
        ),
    ]
