# Generated by Django 5.2.6 on 2026-05-03 11:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_initial'),
        ('attendance', '0002_alter_attendancesession_timetable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancesession',
            name='timetable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sessions', to='academics.timetable'),
        ),
    ]
