# Generated by Django 5.2.6 on 2026-08-18 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0016_alter_batch_unique_together_batch_institute_and_more'),
        ('attendance', '0003_alter_attendancesession_timetable'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='institute',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_sessions', to='academics.institute'),
        ),
    ]
