# Generated by Django 5.2.6 on 2025-09-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance_created_at_attendance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_active',
        ),
    ]
