# Generated by Django 5.2.6 on 2026-09-16 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_attendancesession_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='is_exam',
            field=models.BooleanField(default=False),
        ),
    ]
