# Generated by Django 5.2.6 on 2026-09-18 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesession_is_exam'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='leave_reason',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
