# Generated by Django 5.2.6 on 2025-10-25 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0006_attendancesession_attendancerecord_delete_attendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancesession',
            name='end_time',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='start_time',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
