# Generated by Django 5.2.6 on 2025-10-26 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0015_alter_batch_classs'),
        ('attendance', '0007_attendancesession_end_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancesession',
            old_name='end_time',
            new_name='time',
        ),
        migrations.RemoveField(
            model_name='attendancesession',
            name='start_time',
        ),
        migrations.AddField(
            model_name='attendancesession',
            name='batch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='academics.batch'),
        ),
    ]
