# Generated by Django 5.2.6 on 2026-02-15 08:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0008_rename_end_time_attendancesession_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendancesession',
            old_name='batch',
            new_name='classs',
        ),
        migrations.AlterField(
            model_name='attendancesession',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
