# Generated by Django 5.2.6 on 2026-09-03 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0019_institute_created_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(help_text='Format: YYYY-MM', max_length=7)),
                ('pay_type', models.CharField(choices=[('hourly', 'Hourly'), ('monthly', 'Monthly')], default='monthly', max_length=10)),
                ('base_salary', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate_per_unit', models.DecimalField(decimal_places=2, default=0, help_text='Rate per hour for hourly pay type', max_digits=10)),
                ('units_completed', models.DecimalField(blank=True, decimal_places=2, help_text='Hours worked (for hourly pay type)', max_digits=8, null=True)),
                ('allowances', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, help_text='Manual/other deductions', max_digits=10)),
                ('advance_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('unpaid_leave_deduction', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('pf_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=12)),
                ('pf_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or fixed amount for PF', max_digits=8)),
                ('tax_type', models.CharField(choices=[('none', 'None'), ('percentage', 'Percentage'), ('fixed', 'Fixed Amount')], default='none', max_length=12)),
                ('tax_value', models.DecimalField(decimal_places=2, default=0, help_text='Percentage or fixed amount for Tax', max_digits=8)),
                ('status', models.CharField(choices=[('configured', 'Configured'), ('draft', 'Draft')], default='configured', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teacher_salaries', to='academics.institute')),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_configs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payroll_teacher_salary',
                'ordering': ['-month', 'teacher__name'],
                'unique_together': {('teacher', 'month')},
            },
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('upi', 'UPI'), ('cheque', 'Cheque')], default='bank_transfer', max_length=15)),
                ('transaction_id', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('teacher', models.ForeignKey(limit_choices_to={'user_type': 'teacher'}, on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to=settings.AUTH_USER_MODEL)),
                ('salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='payroll.teachersalary')),
            ],
            options={
                'db_table': 'payroll_salary_payment',
                'ordering': ['-paid_on'],
            },
        ),
    ]
