# Generated by Django 5.2.6 on 2026-08-31 18:20

import apps.notifications.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.CharField(default=apps.notifications.models.generate_notif_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
    ]
