# Generated by Django 5.2.6 on 2026-09-02 19:10

import apps.notifications.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.CharField(default=apps.notifications.models.generate_notif_id, editable=False, max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='notificationhistory',
            index=models.Index(fields=['user', 'is_read'], name='notif_hist_user_isread_idx'),
        ),
    ]
