# Generated by Django 5.2.6 on 2026-09-02 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationhistory_id_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='notificationhistory',
            name='notif_hist_user_isread_idx',
        ),
    ]
