# Generated by Django 5.2.6 on 2026-09-03 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_alter_notificationhistory_id'),
        ('notifications', '0003_remove_notificationhistory_notif_hist_user_isread_idx'),
    ]

    operations = [
    ]
