# Generated by Django 5.2.6 on 2026-09-03 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_merge_20260903_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificationhistory',
            name='broadcast_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='delivery_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('DELIVERED', 'Delivered'), ('READ', 'Read')], default='PENDING', max_length=10),
        ),
        migrations.AddField(
            model_name='notificationhistory',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
