# Generated by Django 5.2.6 on 2026-09-09 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_add_broadcast_delivery_receipt_fields'),
    ]

    operations = [
        migrations.RunSQL(
            sql="TRUNCATE TABLE notification_history;",
            reverse_sql=""
        ),
        migrations.AlterField(
            model_name='notificationhistory',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
